vm:
    box: rackspace
    hostname: master
    provider:
        rackspace:
            server_name: ~
            image: ~
            region: ~
            size: ~
            username: ~
            api_key: ~
    provision:
        puppet:
            manifests_path: "puppet/manifests"
            options:
                - "--verbose"
                - "--hiera_config /vagrant/hiera.yaml"
                - "--parser future"
    synced_folder: []

ssh:
    host: ~
    port: ~
    private_key_path: ~
    public_key_path: ~
    username: ~
    guest_port: ~
    keep_alive: true
    forward_agent: false
    forward_x11: false
    shell: bash -l

vagrant:
    host: :detect
