vm:
    box: debian-wheezy72-x64-vbox43
    box_url: https://puphpet.s3.amazonaws.com/debian-wheezy72-x64-vbox43.box
    hostname: ~
    network:
        private_network: 192.168.56.101
        forwarded_port: []
    provider:
        virtualbox:
            modifyvm:
                name: my-vm-box
                natdnshostresolver1: on
                memory: 512
            setextradata:
                "VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root": 1
    provision:
        puppet:
            manifests_path: "puppet/manifests"
            options:
                - "--verbose"
                - "--hiera_config /vagrant/hiera.yaml"
                - "--parser future"
    synced_folder: []
    usable_port_range: 2200..2250

ssh:
    host: ~
    port: ~
    private_key_path: ~
    username: vagrant
    guest_port: ~
    keep_alive: true
    forward_agent: false
    forward_x11: false
    shell: bash -l

vagrant:
    host: :detect
