vm:
    provider:
        virtualbox: []
    synced_folder:
        -
            source: ./
            target: /var/www
            id: vagrant-root
            nfs: 'false'
    network:
        forwarded_port:
            -
                guest: ~
                host: ~
    provision:
        puppet:
            options:
                - "--verbose"
                - "--hiera_config /vagrant/hiera.yaml"
                - "--parser future"
ssh:
    forward_agent: true
